spring:
  application:
    name: airbob

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

  flyway:
    enabled: true               # Flyway 사용 활성화
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    locations: classpath:db/migration  # 마이그레이션 파일 위치(기본값)
    baseline-on-migrate: true   # 기존 DB에 적용 시 필수(옵션)
    baseline-version: 1          # Baseline 기준 버전(옵션)

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTIC_PASSWORD}
    connection-timeout: 10s
    socket-timeout: 30s

  kafka:
    consumer:
      bootstrap-servers: localhost:9092 # Docker 외부에서 접속 시 localhost, 내부에서는 kafka:9092
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
google:
  api:
    key: ${GOOGLE_API_KEY}

ipinfo:
  api:
    token: ${IPINFO_API_TOKEN}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
  notification:
    enabled: true

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY}
    base-url: https://api.tosspayments.com
