spring:
  application:
    name: airbob

  profiles:
    active: dev

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  flyway:
    enabled: true               # Flyway 사용 활성화
    locations: classpath:db/migration  # 마이그레이션 파일 위치(기본값)
    baseline-on-migrate: true   # 기존 DB에 적용 시 필수(옵션)
    baseline-version: 1          # Baseline 기준 버전(옵션)

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.kafka.dead-letter-publishing.topic-name: PAYMENT.events.DLT
    listener:
      ack-mode: MANUAL
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

google:
  api:
    key: ${GOOGLE_API_KEY}

ipinfo:
  api:
    token: ${IPINFO_API_TOKEN}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
  notification:
    enabled: true

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY}
    base-url: https://api.tosspayments.com

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
